document.writeln('<div id="lucky-number-calculator-and-results-container">');
document.writeln('<div id="lucky-number-calculator-form-container">');
document.writeln('');
document.writeln('<h3>Daily Lucky Numbers Calculator</h3>');
document.writeln('');
document.writeln('<p class="name-label">');
document.writeln('Birth name (required).');
document.writeln('</p>');
document.writeln('');
document.writeln('<input type="text" id="lucky-numbers-fullname">');
document.writeln('');
document.writeln('<p class="date-label">');
document.writeln('Birth date (required):');
document.writeln('</p>');
document.writeln('');
document.writeln('<table border="0" cellpadding="0" cellspacing="0">');
document.writeln('<tr>');
document.writeln('');
document.writeln('<td valign="top">');
document.writeln('Month:');
document.writeln('<br>');
document.writeln('<select id="lucky-numbers-monthdrop">');
document.writeln('<option value=""></option>');
document.writeln('<option value="January">January</option>');
document.writeln('<option value="February">February</option>');
document.writeln('<option value="March">March</option>');
document.writeln('<option value="April">April</option>');
document.writeln('<option value="May">May</option>');
document.writeln('<option value="June">June</option>');
document.writeln('<option value="July">July</option>');
document.writeln('<option value="August">August</option>');
document.writeln('<option value="September">September</option>');
document.writeln('<option value="October">October</option>');
document.writeln('<option value="November">November</option>');
document.writeln('<option value="December">December</option>');
document.writeln('</select>');
document.writeln('</td>');
document.writeln('');
document.writeln('<td valign="top" style="padding-left:15px; padding-right:15px;">');
document.writeln('Day:');
document.writeln('<br>');
document.writeln('<select id="lucky-numbers-daydrop">');
document.writeln('<option value=""></option>');
document.writeln('<option value="1">1</option>');
document.writeln('<option value="2">2</option>');
document.writeln('<option value="3">3</option>');
document.writeln('<option value="4">4</option>');
document.writeln('<option value="5">5</option>');
document.writeln('<option value="6">6</option>');
document.writeln('<option value="7">7</option>');
document.writeln('<option value="8">8</option>');
document.writeln('<option value="9">9</option>');
document.writeln('<option value="10">10</option>');
document.writeln('<option value="11">11</option>');
document.writeln('<option value="12">12</option>');
document.writeln('<option value="13">13</option>');
document.writeln('<option value="14">14</option>');
document.writeln('<option value="15">15</option>');
document.writeln('<option value="16">16</option>');
document.writeln('<option value="17">17</option>');
document.writeln('<option value="18">18</option>');
document.writeln('<option value="19">19</option>');
document.writeln('<option value="20">20</option>');
document.writeln('<option value="21">21</option>');
document.writeln('<option value="22">22</option>');
document.writeln('<option value="23">23</option>');
document.writeln('<option value="24">24</option>');
document.writeln('<option value="25">25</option>');
document.writeln('<option value="26">26</option>');
document.writeln('<option value="27">27</option>');
document.writeln('<option value="28">28</option>');
document.writeln('<option value="29">29</option>');
document.writeln('<option value="30">30</option>');
document.writeln('<option value="31">31</option>');
document.writeln('</select>');
document.writeln('</td>');
document.writeln('');
document.writeln('<td valign="top">');
document.writeln('Year:');
document.writeln('<br>');
document.writeln('<select id="lucky-numbers-yeardrop">');
document.writeln('<option value=""></option>');
document.writeln('<option value="1945">1945</option>');
document.writeln('<option value="1946">1946</option>');
document.writeln('<option value="1947">1947</option>');
document.writeln('<option value="1948">1948</option>');
document.writeln('<option value="1949">1949</option>');
document.writeln('<option value="1950">1950</option>');
document.writeln('<option value="1951">1951</option>');
document.writeln('<option value="1952">1952</option>');
document.writeln('<option value="1953">1953</option>');
document.writeln('<option value="1954">1954</option>');
document.writeln('<option value="1955">1955</option>');
document.writeln('<option value="1956">1956</option>');
document.writeln('<option value="1957">1957</option>');
document.writeln('<option value="1958">1958</option>');
document.writeln('<option value="1959">1959</option>');
document.writeln('<option value="1960">1960</option>');
document.writeln('<option value="1961">1961</option>');
document.writeln('<option value="1962">1962</option>');
document.writeln('<option value="1963">1963</option>');
document.writeln('<option value="1964">1964</option>');
document.writeln('<option value="1965">1965</option>');
document.writeln('<option value="1966">1966</option>');
document.writeln('<option value="1967">1967</option>');
document.writeln('<option value="1968">1968</option>');
document.writeln('<option value="1969">1969</option>');
document.writeln('<option value="1970">1970</option>');
document.writeln('<option value="1971">1971</option>');
document.writeln('<option value="1972">1972</option>');
document.writeln('<option value="1973">1973</option>');
document.writeln('<option value="1974">1974</option>');
document.writeln('<option value="1975">1975</option>');
document.writeln('<option value="1976">1976</option>');
document.writeln('<option value="1977">1977</option>');
document.writeln('<option value="1978">1978</option>');
document.writeln('<option value="1979">1979</option>');
document.writeln('<option value="1980">1980</option>');
document.writeln('<option value="1981">1981</option>');
document.writeln('<option value="1982">1982</option>');
document.writeln('<option value="1983">1983</option>');
document.writeln('<option value="1984">1984</option>');
document.writeln('<option value="1985">1985</option>');
document.writeln('<option value="1986">1986</option>');
document.writeln('<option value="1987">1987</option>');
document.writeln('<option value="1988">1988</option>');
document.writeln('<option value="1989">1989</option>');
document.writeln('<option value="1990">1990</option>');
document.writeln('<option value="1991">1991</option>');
document.writeln('<option value="1992">1992</option>');
document.writeln('<option value="1993">1993</option>');
document.writeln('<option value="1994">1994</option>');
document.writeln('<option value="1995">1995</option>');
document.writeln('<option value="1996">1996</option>');
document.writeln('<option value="1997">1997</option>');
document.writeln('<option value="1998">1998</option>');
document.writeln('<option value="1999">1999</option>');
document.writeln('<option value="2000">2000</option>');
document.writeln('<option value="2001">2001</option>');
document.writeln('<option value="2002">2002</option>');
document.writeln('<option value="2003">2003</option>');
document.writeln('<option value="2004">2004</option>');
document.writeln('</select>');
document.writeln('</td>');
document.writeln('');
document.writeln('</tr>');
document.writeln('</table>');
document.writeln('');
document.writeln('<p>');
document.writeln('<input type="button" onclick="SubmitFormToCalculator()" value="Today\'s Lucky Numbers">');
document.writeln('</p>');
document.writeln('');
document.writeln('</div><'+'!-- id="lucky-number-calculator-form-container" --'+'>');
document.writeln('<scr'+'ipt>');
document.writeln('function SubmitFormToCalculator()');
document.writeln('{');
document.writeln('    var http;');
document.writeln('    var err = new Array();');
document.writeln('    if( ! document.getElementById("lucky-numbers-fullname").value.match(/\\w/) ) { err.push(\'A name needs to be provided.\'); }');
document.writeln('    var drpdn = document.getElementById("lucky-numbers-monthdrop");');
document.writeln('    var opt = drpdn.selectedIndex;');
document.writeln('    if( ! drpdn.options[opt].value.match(/\\w/) ) { err.push(\'A month needs to be selected.\'); }');
document.writeln('    drpdn = document.getElementById("lucky-numbers-daydrop");');
document.writeln('    opt = drpdn.selectedIndex;');
document.writeln('    if( ! drpdn.options[opt].value.match(/\\d/) ) { err.push(\'A day needs to be selected.\'); }');
document.writeln('    drpdn = document.getElementById("lucky-numbers-yeardrop");');
document.writeln('    opt = drpdn.selectedIndex;');
document.writeln('    if( ! drpdn.options[opt].value.match(/\\d/) ) { err.push(\'A year needs to be selected.\'); }');
document.writeln('    if( ! err.length )');
document.writeln('    {');
document.writeln('        http = new XMLHttpRequest();');
document.writeln('        if( ! http ) { err.push(\'Sorry, unable to connect to the server.\'); }');
document.writeln('    }');
document.writeln('    if( err.length )');
document.writeln('    {');
document.writeln('        alert("\\n" + err.join("\\n\\n") + "\\n\\n.");');
document.writeln('        return false;');
document.writeln('    }');
document.writeln('	var params = new Array();');
document.writeln('	params.push( encodeURIComponent("fullname") + "=" + encodeURIComponent(document.getElementById("lucky-numbers-fullname").value) );');
document.writeln('    var drpdn = document.getElementById("lucky-numbers-monthdrop");');
document.writeln('    var opt = drpdn.selectedIndex;');
document.writeln('	params.push( encodeURIComponent("lucky-numbers-monthdrop") + "=" + encodeURIComponent(drpdn.options[opt].value) );');
document.writeln('    drpdn = document.getElementById("lucky-numbers-daydrop");');
document.writeln('    opt = drpdn.selectedIndex;');
document.writeln('	params.push( encodeURIComponent("lucky-numbers-daydrop") + "=" + encodeURIComponent(drpdn.options[opt].value) );');
document.writeln('    drpdn = document.getElementById("lucky-numbers-yeardrop");');
document.writeln('    opt = drpdn.selectedIndex;');
document.writeln('	params.push( encodeURIComponent("lucky-numbers-yeardrop") + "=" + encodeURIComponent(drpdn.options[opt].value) );');
document.writeln('	http.onreadystatechange = function()');
document.writeln('	{ ');
document.writeln('		if(http.readyState == 4)');
document.writeln('		{');
document.writeln('			if(http.status == 200)');
document.writeln('			{');
document.writeln('				//alert(http.responseText);');
document.writeln('				document.getElementById("lucky-number-calculator-and-results-container").innerHTML = http.responseText;');
document.writeln('			}');
document.writeln('			else { alert(\'\\n\\nContent request error, status code:\\n\'+http.status+\' \'+http.statusText); }');
document.writeln('		}');
document.writeln('	}');
document.writeln('	http.open("POST","/luckynumbers/DailyLuckyNumbers.php",true);');
document.writeln('	http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");');
document.writeln('	http.send(params.join("&"));');
document.writeln('	return true;');
document.writeln('} // function SubmitFormToCalculator()');
document.writeln('</scr'+'ipt></div>');
